// Code generated by Ragel; DO NOT EDIT.
package config

import (
 "strconv"
 "strings"
)

%%{
 machine command;
 alphtype byte;
 h = [ \t];
 tail = (h (any - '\n')*)?;
 poe_port = ('no' h+)? 'inline' h+ 'power' h+ ('ethernet' | 'ethe') tail;
 stp_edge = ('no' h+)? 'spanning-tree' h+ '802-1w' h+ 'admin-edge-port' tail;
 stp_root = ('no' h+)? 'spanning-tree' h+ 'root-protect' tail;
 main := (
  stp_edge @{ kind = stpEdge } |
  stp_root @{ kind = stpRoot } |
  (('no' h+)? 'stp-bpdu-guard' tail) @{ kind = stpBPDU } |
  ((('no' h+)? 'spanning-tree' tail) - stp_edge - stp_root) @{ kind = spanningTree } |
  poe_port @{ kind = inlinePowerPort } |
  ((('no' h+)? 'inline' h+ 'power' tail) - poe_port) @{ kind = inlinePower } |
  ('trust' h+ 'dscp' tail) @{ kind = trustDSCP } |
  ('protected-port' tail) @{ kind = protectedPort } |
  ('voice-vlan' tail) @{ kind = voiceVLAN } |
  (('no' h+)? 'lldp' h+ 'run' tail) @{ kind = lldpRun } |
  (('no' h+)? 'lldp' h+ 'med' h+ 'network-policy' tail) @{ kind = lldpMED } |
  (('no' h+)? 'lldp' h+ 'enable' h+ (('receive' | 'transmit') h+)? 'ports' tail) @{ kind = lldpPorts } |
  ('jumbo' tail) @{ kind = jumboMode } |
  ('port-name' tail) @{ kind = portName } |
  ('disable' tail) @{ kind = adminDisable } |
  ('default-vlan-id' (any - '\n')*) @{ kind = defaultVLAN } |
  ('vlan' tail) @{ kind = vlanHeader } |
  ('interface' tail) @{ kind = interfaceStanza } |
  (('ip' h+ 'access-list' | 'ipv6' h+ 'access-list' | 'mac' h+ 'access-list') (any - '\n')*) @{ kind = aclHeader } |
  ((('ip' h+)? 'multicast' tail) - ('multicast' h+ 'limit' tail)) @{ kind = multicastConfig } |
  ('symmetrical-flow-control' h+ (any - '\n')+) @{ kind = symmetricFlowControl } |
  (('broadcast' | 'multicast' | 'unknown-unicast') h+ 'limit' tail) @{ kind = stormLimit }
 );
}%%
%% write data;

func commandKind(data string) (kind kind) {
 p, pe := 0, len(data)
 cs := 0
 %% write init;
 %% write exec;
 if cs < command_first_final { return unknown }
 return kind
}

%%{
 machine words;
 alphtype byte;
 action mark { start = p }
 action word { fields = append(fields, data[start:p]) }
 main := space* ((any - space)+ >mark %word space+)*;
}%%
%% write data;

func commandFields(data string) (fields []string) {
 data += " "
 p, pe := 0, len(data)
 cs, start := 0, 0
 %% write init;
 %% write exec;
 return fields
}

// Syntax recognition and argument capture belong to this machine. Numeric ranges
// and ownership across stanzas are checked by the extractors.
%%{
 machine syntax;
 alphtype byte;
 h = [ \t];
 token = (any - space)+;
 number = '+'? digit+;
 action mark { start = p }
 action value {
  var err error
  parsed.number, err = strconv.ParseInt(data[start:p], 10, 64)
  numberValid = numberValid && err == nil
 }
 action name { parsed.name = data[start:p] }
 action unit { parsed.unit = data[start:p] }
 action options { parsed.options = true }
 flag = 'trust' h+ 'dscp' | 'protected-port' | 'jumbo' | 'disable';
 voice = 'voice-vlan' h+ ([1-9] digit*) >mark %value;
 storm = ('broadcast' | 'multicast' | 'unknown-unicast') >mark %name
         h+ 'limit' h+ number >mark %value
         (h+ ('kbps' | 'pps') >mark %unit)?
         (h+ ('log' | 'threshold') %options (h+ token)*)?;
 vlan = ('default-vlan-id' h+ number >mark %value) |
        ('vlan' h+ number >mark %value (h+ token)*);
 interface = 'interface' h+ (token (h+ token)*) >mark
             %{ parsed.name = strings.Join(commandFields(data[start:p]), " ") };
 acl = (
       ('ip' h+ 'access-list' h+ 'standard') %{ parsed.family = "ipv4_standard" } |
       ('ip' h+ 'access-list' h+ 'extended') %{ parsed.family = "ipv4_extended" } |
       ('ipv6' h+ 'access-list') %{ parsed.family = "ipv6" } |
       ('mac' h+ 'access-list') %{ parsed.family = "mac" }
       ) h+ token >mark %name;
 multicast = (('ip' h+ %{ parsed.global = true })? 'multicast' h+ (
       ('active' | 'passive' | 'disable-igmp-snoop') >mark %name |
       'version' %{ parsed.name = "version" } h+ number >mark %value |
       (token - ('active' | 'passive' | 'disable-igmp-snoop' | 'version')) (h+ token)*
       )) - ('multicast' h+ 'limit' (h (any - '\n')*)?);
 port_id = [1-9] digit* '/' [1-9] digit* '/' [1-9] digit*;
 action firstPort {
  id, valid := parseEthernetPort(data[start:p])
  numberValid = numberValid && valid
  parsed.portRanges = append(parsed.portRanges, portRange{first:id, last:id})
 }
 action lastPort {
  id, valid := parseEthernetPort(data[start:p])
  numberValid = numberValid && valid
  parsed.portRanges[len(parsed.portRanges)-1].last = id
 }
 port_range = ('ethe' | 'ethernet') h+ port_id >mark %firstPort
              (h+ 'to' h+ port_id >mark %lastPort)?;
 port_list = 'all' %{ parsed.allPorts = true } | port_range (h+ port_range)*;
 application = 'voice' | 'voice-signaling' | 'guest-voice' | 'guest-voice-signaling' |
               'softphone-voice' | 'streaming-video' | 'video-conferencing' | 'video-signaling';
 med = 'lldp' h+ 'med' h+ 'network-policy' h+ 'application' h+ application >mark %name h+ (
       'untagged' %{ parsed.med.Traffic = "untagged" } |
       ('priority-tagged' %{ parsed.med.Traffic = "priority-tagged" } |
        'tagged' %{ parsed.med.Traffic = "tagged" } h+ 'vlan' h+ digit+ >mark %value %{ parsed.med.VLAN = parsed.number })
       h+ 'priority' h+ digit+ >mark %value %{ parsed.med.Priority = parsed.number }
       ) h+ 'dscp' h+ digit+ >mark %value %{ parsed.med.DSCP = parsed.number }
       h+ 'ports' h+ port_list;
 lldp = ('no' h+ %{ parsed.negated = true })? 'lldp' h+ (
  'run' | 'enable' h+ (('receive' | 'transmit') >mark %{ parsed.direction = data[start:p] } h+)?
  'ports' h+ port_list
 );
 poe_target = ('ethernet' | 'ethe') h+ port_id >mark %name;
 poe_priority = 'priority' h+ digit+ >mark %value %{
  numberValid = numberValid && parsed.poeFields & 1 == 0
  parsed.poeFields |= 1
  parsed.poe.Priority = parsed.number
 };
 poe_class = 'power-by-class' h+ digit+ >mark %value %{
  numberValid = numberValid && parsed.poeFields & 6 == 0
  parsed.poeFields |= 2
  parsed.poe.PowerByClass = parsed.number
 };
 poe_limit = 'power-limit' h+ digit+ >mark %value %{
  numberValid = numberValid && parsed.poeFields & 6 == 0
  parsed.poeFields |= 4
  parsed.poe.PowerLimitMilliwatts = parsed.number
 };
 poe = ('no' h+ 'inline' h+ 'power' %{ parsed.poe.Enabled = false } (h+ poe_target)?) |
       ('inline' h+ 'power' (h+ poe_target)? (h+ (poe_priority | poe_class | poe_limit))*);
 stp = 'spanning-tree' (h+ '802-1w' %{ parsed.family = "rstp" })?
       (h+ 'priority' h+ number >mark %value %options)?;
 stp_flag = ('no' h+ %{ parsed.negated = true })?
            ('spanning-tree' h+ ('802-1w' h+ 'admin-edge-port' | 'root-protect') | 'stp-bpdu-guard');
 main := (stp_flag | stp | poe | med | lldp | flag | voice | storm | vlan | interface | acl | multicast |
          'port-name' h+ (any - '\n')+ >mark %name |
          'symmetrical-flow-control' h+ token (h+ token)*) '\n';
}%%
%% write data;

func parseCommand(data string) (parsed parsedCommand) {
 parsed.kind = commandKind(data)
 if parsed.kind == spanningTree { parsed.family = "stp"; parsed.number = 32768 }
 if parsed.kind == inlinePower || parsed.kind == inlinePowerPort { parsed.poe = PoEPolicy{Enabled: true, Priority: 3} }
 if parsed.kind == unknown { return parsed }
 data += "\n"
 p, pe := 0, len(data)
 cs, start := 0, 0
 numberValid := true
 %% write init;
 %% write exec;
 parsed.valid = cs >= syntax_first_final && numberValid
 return parsed
}

%%{
 machine ethernet_port;
 alphtype byte;
 action mark { start = p }
 action component {
  var err error
  id[index], err = strconv.ParseUint(data[start:p], 10, 64)
  valid = valid && err == nil
  index++
 }
 component = ([1-9] digit*) >mark %component;
 main := component '/' component '/' component '\n';
}%%
%% write data;

func parseEthernetPort(data string) (id [3]uint64, valid bool) {
 data += "\n"
 p, pe := 0, len(data)
 cs, start, index := 0, 0, 0
 valid = true
 %% write init;
 %% write exec;
 return id, valid && cs >= ethernet_port_first_final
}
