// Code generated by Ragel; DO NOT EDIT.
package config

import (
 "strconv"
 "strings"
)

%%{
 machine command;
 alphtype byte;
 h = [ \t];
 tail = (h (any - '\n')*)?;
 main := (
  ('trust' h+ 'dscp' tail) @{ kind = trustDSCP } |
  ('protected-port' tail) @{ kind = protectedPort } |
  ('voice-vlan' tail) @{ kind = voiceVLAN } |
  (('no' h+)? 'lldp' h+ 'run' tail) @{ kind = lldpRun } |
  ('jumbo' tail) @{ kind = jumboMode } |
  ('port-name' tail) @{ kind = portName } |
  ('disable' tail) @{ kind = adminDisable } |
  ('default-vlan-id' (any - '\n')*) @{ kind = defaultVLAN } |
  ('vlan' tail) @{ kind = vlanHeader } |
  ('interface' tail) @{ kind = interfaceStanza } |
  (('ip' h+ 'access-list' | 'ipv6' h+ 'access-list' | 'mac' h+ 'access-list') (any - '\n')*) @{ kind = aclHeader } |
  ((('ip' h+)? 'multicast' tail) - ('multicast' h+ 'limit' tail)) @{ kind = multicastConfig } |
  ('symmetrical-flow-control' h+ (any - '\n')+) @{ kind = symmetricFlowControl } |
  (('broadcast' | 'multicast' | 'unknown-unicast') h+ 'limit' tail) @{ kind = stormLimit }
 );
}%%
%% write data;

func commandKind(data string) (kind kind) {
 p, pe := 0, len(data)
 cs := 0
 %% write init;
 %% write exec;
 if cs < command_first_final { return unknown }
 return kind
}

%%{
 machine words;
 alphtype byte;
 action mark { start = p }
 action word { fields = append(fields, data[start:p]) }
 main := space* ((any - space)+ >mark %word space+)*;
}%%
%% write data;

func commandFields(data string) (fields []string) {
 data += " "
 p, pe := 0, len(data)
 cs, start := 0, 0
 %% write init;
 %% write exec;
 return fields
}

// Syntax recognition and argument capture belong to this machine. Numeric ranges,
// duplicate settings and ownership across stanzas are checked by the extractors.
%%{
 machine syntax;
 alphtype byte;
 h = [ \t];
 token = (any - space)+;
 number = '+'? digit+;
 action mark { start = p }
 action value {
  var err error
  parsed.number, err = strconv.ParseInt(data[start:p], 10, 64)
  numberValid = err == nil
 }
 action name { parsed.name = data[start:p] }
 action unit { parsed.unit = data[start:p] }
 action options { parsed.options = true }
 flag = 'trust' h+ 'dscp' | 'protected-port' | 'jumbo' | 'disable';
 voice = 'voice-vlan' h+ ([1-9] digit*) >mark %value;
 storm = ('broadcast' | 'multicast' | 'unknown-unicast') >mark %name
         h+ 'limit' h+ number >mark %value
         (h+ ('kbps' | 'pps') >mark %unit)?
         (h+ ('log' | 'threshold') %options (h+ token)*)?;
 vlan = ('default-vlan-id' h+ number >mark %value) |
        ('vlan' h+ number >mark %value (h+ token)*);
 interface = 'interface' h+ (token (h+ token)*) >mark
             %{ parsed.name = strings.Join(commandFields(data[start:p]), " ") };
 acl = (
       ('ip' h+ 'access-list' h+ 'standard') %{ parsed.family = "ipv4_standard" } |
       ('ip' h+ 'access-list' h+ 'extended') %{ parsed.family = "ipv4_extended" } |
       ('ipv6' h+ 'access-list') %{ parsed.family = "ipv6" } |
       ('mac' h+ 'access-list') %{ parsed.family = "mac" }
       ) h+ token >mark %name;
 multicast = (('ip' h+ %{ parsed.global = true })? 'multicast' h+ (
       ('active' | 'passive' | 'disable-igmp-snoop') >mark %name |
       'version' %{ parsed.name = "version" } h+ number >mark %value |
       (token - ('active' | 'passive' | 'disable-igmp-snoop' | 'version')) (h+ token)*
       )) - ('multicast' h+ 'limit' (h (any - '\n')*)?);
 lldp = ('no' h+ %{ parsed.negated = true })? 'lldp' h+ 'run';
 main := (lldp | flag | voice | storm | vlan | interface | acl | multicast |
          'port-name' h+ (any - '\n')+ >mark %name |
          'symmetrical-flow-control' h+ token (h+ token)*) '\n';
}%%
%% write data;

func parseCommand(data string) (parsed parsedCommand) {
 parsed.kind = commandKind(data)
 if parsed.kind == unknown { return parsed }
 data += "\n"
 p, pe := 0, len(data)
 cs, start := 0, 0
 numberValid := true
 %% write init;
 %% write exec;
 parsed.valid = cs >= syntax_first_final && numberValid
 return parsed
}
