// Code generated by Ragel; DO NOT EDIT.
//
//line command.rl:1
package config

//line command.rl:18

//line command_parser.go:8
var _command_actions []byte = []byte{
	0, 1, 0, 1, 1, 1, 2, 1, 3,
	1, 4, 1, 5, 1, 6,
}

var _command_key_offsets []byte = []byte{
	0, 0, 8, 9, 10, 11, 12, 13,
	14, 15, 16, 18, 21, 22, 23, 24,
	25, 26, 27, 28, 29, 30, 31, 32,
	33, 34, 35, 36, 37, 38, 39, 41,
	42, 43, 44, 45, 46, 47, 48, 49,
	50, 51, 52, 53, 54, 55, 56, 57,
	58, 59, 60, 61, 62, 63, 64, 66,
	69, 70, 71, 72, 73, 74, 75, 76,
	77, 78, 79, 80, 81, 82, 83, 84,
	85, 86, 87, 88, 89, 90, 92, 93,
	95, 96, 98, 99, 101, 102, 104, 105,
	107, 108, 110,
}

var _command_trans_keys []byte = []byte{
	98, 100, 106, 109, 112, 116, 117, 118,
	114, 111, 97, 100, 99, 97, 115, 116,
	9, 32, 9, 32, 108, 105, 109, 105,
	116, 105, 115, 97, 98, 108, 101, 117,
	109, 98, 111, 117, 108, 116, 105, 111,
	114, 114, 116, 45, 110, 97, 109, 101,
	111, 116, 101, 99, 116, 101, 100, 45,
	112, 111, 114, 116, 114, 117, 115, 116,
	9, 32, 9, 32, 100, 115, 99, 112,
	110, 107, 110, 111, 119, 110, 45, 117,
	110, 111, 105, 99, 101, 45, 118, 108,
	97, 110, 9, 32, 10, 9, 32, 10,
	9, 32, 10, 9, 32, 10, 9, 32,
	10, 9, 32, 10, 9, 32, 10,
}

var _command_single_lengths []byte = []byte{
	0, 8, 1, 1, 1, 1, 1, 1,
	1, 1, 2, 3, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 2, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 2, 3,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 2, 1, 2,
	1, 2, 1, 2, 1, 2, 1, 2,
	1, 2, 1,
}

var _command_range_lengths []byte = []byte{
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0,
}

var _command_index_offsets []int16 = []int16{
	0, 0, 9, 11, 13, 15, 17, 19,
	21, 23, 25, 28, 32, 34, 36, 38,
	40, 42, 44, 46, 48, 50, 52, 54,
	56, 58, 60, 62, 64, 66, 68, 71,
	73, 75, 77, 79, 81, 83, 85, 87,
	89, 91, 93, 95, 97, 99, 101, 103,
	105, 107, 109, 111, 113, 115, 117, 120,
	124, 126, 128, 130, 132, 134, 136, 138,
	140, 142, 144, 146, 148, 150, 152, 154,
	156, 158, 160, 162, 164, 166, 169, 171,
	174, 176, 179, 181, 184, 186, 189, 191,
	194, 196, 199,
}

var _command_indicies []byte = []byte{
	0, 2, 3, 4, 5, 6, 7, 8,
	1, 9, 1, 10, 1, 11, 1, 12,
	1, 13, 1, 14, 1, 15, 1, 16,
	1, 17, 17, 1, 17, 17, 18, 1,
	19, 1, 20, 1, 21, 1, 22, 1,
	23, 1, 24, 1, 25, 1, 26, 1,
	27, 1, 28, 1, 29, 1, 30, 1,
	31, 1, 32, 1, 33, 1, 34, 1,
	35, 1, 12, 1, 36, 37, 1, 38,
	1, 39, 1, 40, 1, 41, 1, 42,
	1, 43, 1, 44, 1, 45, 1, 46,
	1, 47, 1, 48, 1, 49, 1, 50,
	1, 51, 1, 52, 1, 53, 1, 54,
	1, 55, 1, 56, 1, 57, 1, 58,
	1, 59, 1, 60, 1, 61, 61, 1,
	61, 61, 62, 1, 63, 1, 64, 1,
	65, 1, 66, 1, 67, 1, 68, 1,
	69, 1, 70, 1, 71, 1, 72, 1,
	73, 1, 35, 1, 74, 1, 75, 1,
	76, 1, 77, 1, 78, 1, 79, 1,
	80, 1, 81, 1, 82, 1, 83, 83,
	1, 1, 83, 84, 84, 1, 1, 84,
	85, 85, 1, 1, 85, 86, 86, 1,
	1, 86, 87, 87, 1, 1, 87, 88,
	88, 1, 1, 88, 89, 89, 1, 1,
	89,
}

var _command_trans_targs []byte = []byte{
	2, 0, 16, 22, 26, 30, 50, 59,
	68, 3, 4, 5, 6, 7, 8, 9,
	10, 11, 12, 13, 14, 15, 77, 17,
	18, 19, 20, 21, 79, 23, 24, 25,
	81, 27, 28, 29, 31, 38, 32, 33,
	34, 35, 36, 37, 83, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49,
	85, 51, 52, 53, 54, 55, 56, 57,
	58, 87, 60, 61, 62, 63, 64, 65,
	66, 67, 69, 70, 71, 72, 73, 74,
	75, 76, 89, 78, 80, 82, 84, 86,
	88, 90,
}

var _command_trans_actions []byte = []byte{
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 13, 0,
	0, 0, 0, 0, 11, 0, 0, 0,
	7, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 9, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	3, 0, 0, 0, 0, 0, 0, 0,
	0, 1, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 5, 13, 11, 7, 9, 3,
	1, 5,
}

const (
	command_start       int = 1
	command_first_final int = 77
	command_error       int = 0
)

const command_en_main int = 1

//line command.rl:20

func commandKind(data string) (kind kind) {
	p, pe := 0, len(data)
	cs := 0

//line command_parser.go:161
	{
		cs = command_start
	}

//line command.rl:25

//line command_parser.go:166
	{
		var _klen int
		var _trans int
		var _acts int
		var _nacts uint
		var _keys int
		if p == pe {
			goto _test_eof
		}
		if cs == 0 {
			goto _out
		}
	_resume:
		_keys = int(_command_key_offsets[cs])
		_trans = int(_command_index_offsets[cs])

		_klen = int(_command_single_lengths[cs])
		if _klen > 0 {
			_lower := int(_keys)
			var _mid int
			_upper := int(_keys + _klen - 1)
			for {
				if _upper < _lower {
					break
				}

				_mid = _lower + ((_upper - _lower) >> 1)
				switch {
				case data[p] < _command_trans_keys[_mid]:
					_upper = _mid - 1
				case data[p] > _command_trans_keys[_mid]:
					_lower = _mid + 1
				default:
					_trans += int(_mid - int(_keys))
					goto _match
				}
			}
			_keys += _klen
			_trans += _klen
		}

		_klen = int(_command_range_lengths[cs])
		if _klen > 0 {
			_lower := int(_keys)
			var _mid int
			_upper := int(_keys + (_klen << 1) - 2)
			for {
				if _upper < _lower {
					break
				}

				_mid = _lower + (((_upper - _lower) >> 1) & ^1)
				switch {
				case data[p] < _command_trans_keys[_mid]:
					_upper = _mid - 2
				case data[p] > _command_trans_keys[_mid+1]:
					_lower = _mid + 2
				default:
					_trans += int((_mid - int(_keys)) >> 1)
					goto _match
				}
			}
			_trans += _klen
		}

	_match:
		_trans = int(_command_indicies[_trans])
		cs = int(_command_trans_targs[_trans])

		if _command_trans_actions[_trans] == 0 {
			goto _again
		}

		_acts = int(_command_trans_actions[_trans])
		_nacts = uint(_command_actions[_acts])
		_acts++
		for ; _nacts > 0; _nacts-- {
			_acts++
			switch _command_actions[_acts-1] {
			case 0:
//line command.rl:10
				kind = trustDSCP
			case 1:
//line command.rl:11
				kind = protectedPort
			case 2:
//line command.rl:12
				kind = voiceVLAN
			case 3:
//line command.rl:13
				kind = jumboMode
			case 4:
//line command.rl:14
				kind = portName
			case 5:
//line command.rl:15
				kind = adminDisable
			case 6:
//line command.rl:16
				kind = stormLimit
//line command_parser.go:266
			}
		}

	_again:
		if cs == 0 {
			goto _out
		}
		p++
		if p != pe {
			goto _resume
		}
	_test_eof:
		{
		}
	_out:
		{
		}
	}

//line command.rl:26
	if cs < command_first_final {
		return unknown
	}
	return kind
}

//line command.rl:36

//line command_parser.go:288
var _words_actions []byte = []byte{
	0, 1, 0, 1, 1,
}

var _words_key_offsets []byte = []byte{
	0, 3,
}

var _words_trans_keys []byte = []byte{
	32, 9, 13, 32, 9, 13,
}

var _words_single_lengths []byte = []byte{
	1, 1,
}

var _words_range_lengths []byte = []byte{
	1, 1,
}

var _words_index_offsets []byte = []byte{
	0, 3,
}

var _words_trans_targs []byte = []byte{
	1, 1, 0, 1, 1, 0,
}

var _words_trans_actions []byte = []byte{
	3, 3, 0, 0, 0, 1,
}

const (
	words_start       int = 1
	words_first_final int = 1
	words_error       int = -1
)

const words_en_main int = 1

//line command.rl:38

func commandFields(data string) (fields []string) {
	data += " "
	p, pe := 0, len(data)
	cs, start := 0, 0

//line command_parser.go:333
	{
		cs = words_start
	}

//line command.rl:44

//line command_parser.go:338
	{
		var _klen int
		var _trans int
		var _acts int
		var _nacts uint
		var _keys int
		if p == pe {
			goto _test_eof
		}
	_resume:
		_keys = int(_words_key_offsets[cs])
		_trans = int(_words_index_offsets[cs])

		_klen = int(_words_single_lengths[cs])
		if _klen > 0 {
			_lower := int(_keys)
			var _mid int
			_upper := int(_keys + _klen - 1)
			for {
				if _upper < _lower {
					break
				}

				_mid = _lower + ((_upper - _lower) >> 1)
				switch {
				case data[p] < _words_trans_keys[_mid]:
					_upper = _mid - 1
				case data[p] > _words_trans_keys[_mid]:
					_lower = _mid + 1
				default:
					_trans += int(_mid - int(_keys))
					goto _match
				}
			}
			_keys += _klen
			_trans += _klen
		}

		_klen = int(_words_range_lengths[cs])
		if _klen > 0 {
			_lower := int(_keys)
			var _mid int
			_upper := int(_keys + (_klen << 1) - 2)
			for {
				if _upper < _lower {
					break
				}

				_mid = _lower + (((_upper - _lower) >> 1) & ^1)
				switch {
				case data[p] < _words_trans_keys[_mid]:
					_upper = _mid - 2
				case data[p] > _words_trans_keys[_mid+1]:
					_lower = _mid + 2
				default:
					_trans += int((_mid - int(_keys)) >> 1)
					goto _match
				}
			}
			_trans += _klen
		}

	_match:
		cs = int(_words_trans_targs[_trans])

		if _words_trans_actions[_trans] == 0 {
			goto _again
		}

		_acts = int(_words_trans_actions[_trans])
		_nacts = uint(_words_actions[_acts])
		_acts++
		for ; _nacts > 0; _nacts-- {
			_acts++
			switch _words_actions[_acts-1] {
			case 0:
//line command.rl:33
				start = p
			case 1:
//line command.rl:34
				fields = append(fields, data[start:p])
//line command_parser.go:419
			}
		}

	_again:
		p++
		if p != pe {
			goto _resume
		}
	_test_eof:
		{
		}
	}

//line command.rl:45
	return fields
}
