// Code generated by Ragel; DO NOT EDIT.
//
//line command.rl:1
package config

//line command.rl:15

//line command_parser.go:8
var _command_actions []byte = []byte{
	0, 1, 0, 1, 1, 1, 2, 1, 3,
}

var _command_key_offsets []byte = []byte{
	0, 0, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 16, 19, 20, 21, 22,
	23, 24, 25, 26, 27, 28, 29, 30,
	31, 32, 33, 34, 35, 36, 37, 38,
	39, 40, 41, 42, 43, 44, 46, 49,
	50, 51, 52, 53, 54, 55, 56, 57,
	58, 59, 60, 61, 62, 63, 64, 65,
	66, 67, 68, 69, 70, 72, 73, 75,
	76, 78, 79, 81,
}

var _command_trans_keys []byte = []byte{
	98, 109, 112, 116, 117, 118, 114, 111,
	97, 100, 99, 97, 115, 116, 9, 32,
	9, 32, 108, 105, 109, 105, 116, 117,
	108, 116, 105, 114, 111, 116, 101, 99,
	116, 101, 100, 45, 112, 111, 114, 116,
	114, 117, 115, 116, 9, 32, 9, 32,
	100, 115, 99, 112, 110, 107, 110, 111,
	119, 110, 45, 117, 110, 111, 105, 99,
	101, 45, 118, 108, 97, 110, 9, 32,
	10, 9, 32, 10, 9, 32, 10, 9,
	32, 10,
}

var _command_single_lengths []byte = []byte{
	0, 6, 1, 1, 1, 1, 1, 1,
	1, 1, 2, 3, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 2, 3, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 2, 1, 2, 1,
	2, 1, 2, 1,
}

var _command_range_lengths []byte = []byte{
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0,
}

var _command_index_offsets []byte = []byte{
	0, 0, 7, 9, 11, 13, 15, 17,
	19, 21, 23, 26, 30, 32, 34, 36,
	38, 40, 42, 44, 46, 48, 50, 52,
	54, 56, 58, 60, 62, 64, 66, 68,
	70, 72, 74, 76, 78, 80, 83, 87,
	89, 91, 93, 95, 97, 99, 101, 103,
	105, 107, 109, 111, 113, 115, 117, 119,
	121, 123, 125, 127, 129, 132, 134, 137,
	139, 142, 144, 147,
}

var _command_indicies []byte = []byte{
	0, 2, 3, 4, 5, 6, 1, 7,
	1, 8, 1, 9, 1, 10, 1, 11,
	1, 12, 1, 13, 1, 14, 1, 15,
	15, 1, 15, 15, 16, 1, 17, 1,
	18, 1, 19, 1, 20, 1, 21, 1,
	22, 1, 23, 1, 10, 1, 24, 1,
	25, 1, 26, 1, 27, 1, 28, 1,
	29, 1, 30, 1, 31, 1, 32, 1,
	33, 1, 34, 1, 35, 1, 36, 1,
	37, 1, 38, 1, 39, 1, 40, 1,
	41, 41, 1, 41, 41, 42, 1, 43,
	1, 44, 1, 45, 1, 46, 1, 47,
	1, 48, 1, 49, 1, 50, 1, 51,
	1, 52, 1, 53, 1, 23, 1, 54,
	1, 55, 1, 56, 1, 57, 1, 58,
	1, 59, 1, 60, 1, 61, 1, 62,
	1, 63, 63, 1, 1, 63, 64, 64,
	1, 1, 64, 65, 65, 1, 1, 65,
	66, 66, 1, 1, 66,
}

var _command_trans_targs []byte = []byte{
	2, 0, 16, 20, 33, 42, 51, 3,
	4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 60, 17, 18, 19,
	21, 22, 23, 24, 25, 26, 27, 28,
	29, 30, 31, 32, 62, 34, 35, 36,
	37, 38, 39, 40, 41, 64, 43, 44,
	45, 46, 47, 48, 49, 50, 52, 53,
	54, 55, 56, 57, 58, 59, 66, 61,
	63, 65, 67,
}

var _command_trans_actions []byte = []byte{
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 7, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 3, 0, 0, 0,
	0, 0, 0, 0, 0, 1, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 5, 7,
	3, 1, 5,
}

const (
	command_start       int = 1
	command_first_final int = 60
	command_error       int = 0
)

const command_en_main int = 1

//line command.rl:17

func commandKind(data string) (kind kind) {
	p, pe := 0, len(data)
	cs := 0

//line command_parser.go:132
	{
		cs = command_start
	}

//line command.rl:22

//line command_parser.go:137
	{
		var _klen int
		var _trans int
		var _acts int
		var _nacts uint
		var _keys int
		if p == pe {
			goto _test_eof
		}
		if cs == 0 {
			goto _out
		}
	_resume:
		_keys = int(_command_key_offsets[cs])
		_trans = int(_command_index_offsets[cs])

		_klen = int(_command_single_lengths[cs])
		if _klen > 0 {
			_lower := int(_keys)
			var _mid int
			_upper := int(_keys + _klen - 1)
			for {
				if _upper < _lower {
					break
				}

				_mid = _lower + ((_upper - _lower) >> 1)
				switch {
				case data[p] < _command_trans_keys[_mid]:
					_upper = _mid - 1
				case data[p] > _command_trans_keys[_mid]:
					_lower = _mid + 1
				default:
					_trans += int(_mid - int(_keys))
					goto _match
				}
			}
			_keys += _klen
			_trans += _klen
		}

		_klen = int(_command_range_lengths[cs])
		if _klen > 0 {
			_lower := int(_keys)
			var _mid int
			_upper := int(_keys + (_klen << 1) - 2)
			for {
				if _upper < _lower {
					break
				}

				_mid = _lower + (((_upper - _lower) >> 1) & ^1)
				switch {
				case data[p] < _command_trans_keys[_mid]:
					_upper = _mid - 2
				case data[p] > _command_trans_keys[_mid+1]:
					_lower = _mid + 2
				default:
					_trans += int((_mid - int(_keys)) >> 1)
					goto _match
				}
			}
			_trans += _klen
		}

	_match:
		_trans = int(_command_indicies[_trans])
		cs = int(_command_trans_targs[_trans])

		if _command_trans_actions[_trans] == 0 {
			goto _again
		}

		_acts = int(_command_trans_actions[_trans])
		_nacts = uint(_command_actions[_acts])
		_acts++
		for ; _nacts > 0; _nacts-- {
			_acts++
			switch _command_actions[_acts-1] {
			case 0:
//line command.rl:10
				kind = trustDSCP
			case 1:
//line command.rl:11
				kind = protectedPort
			case 2:
//line command.rl:12
				kind = voiceVLAN
			case 3:
//line command.rl:13
				kind = stormLimit
//line command_parser.go:228
			}
		}

	_again:
		if cs == 0 {
			goto _out
		}
		p++
		if p != pe {
			goto _resume
		}
	_test_eof:
		{
		}
	_out:
		{
		}
	}

//line command.rl:23
	if cs < command_first_final {
		return unknown
	}
	return kind
}

//line command.rl:33

//line command_parser.go:250
var _words_actions []byte = []byte{
	0, 1, 0, 1, 1,
}

var _words_key_offsets []byte = []byte{
	0, 3,
}

var _words_trans_keys []byte = []byte{
	32, 9, 13, 32, 9, 13,
}

var _words_single_lengths []byte = []byte{
	1, 1,
}

var _words_range_lengths []byte = []byte{
	1, 1,
}

var _words_index_offsets []byte = []byte{
	0, 3,
}

var _words_trans_targs []byte = []byte{
	1, 1, 0, 1, 1, 0,
}

var _words_trans_actions []byte = []byte{
	3, 3, 0, 0, 0, 1,
}

const (
	words_start       int = 1
	words_first_final int = 1
	words_error       int = -1
)

const words_en_main int = 1

//line command.rl:35

func commandFields(data string) (fields []string) {
	data += " "
	p, pe := 0, len(data)
	cs, start := 0, 0

//line command_parser.go:295
	{
		cs = words_start
	}

//line command.rl:41

//line command_parser.go:300
	{
		var _klen int
		var _trans int
		var _acts int
		var _nacts uint
		var _keys int
		if p == pe {
			goto _test_eof
		}
	_resume:
		_keys = int(_words_key_offsets[cs])
		_trans = int(_words_index_offsets[cs])

		_klen = int(_words_single_lengths[cs])
		if _klen > 0 {
			_lower := int(_keys)
			var _mid int
			_upper := int(_keys + _klen - 1)
			for {
				if _upper < _lower {
					break
				}

				_mid = _lower + ((_upper - _lower) >> 1)
				switch {
				case data[p] < _words_trans_keys[_mid]:
					_upper = _mid - 1
				case data[p] > _words_trans_keys[_mid]:
					_lower = _mid + 1
				default:
					_trans += int(_mid - int(_keys))
					goto _match
				}
			}
			_keys += _klen
			_trans += _klen
		}

		_klen = int(_words_range_lengths[cs])
		if _klen > 0 {
			_lower := int(_keys)
			var _mid int
			_upper := int(_keys + (_klen << 1) - 2)
			for {
				if _upper < _lower {
					break
				}

				_mid = _lower + (((_upper - _lower) >> 1) & ^1)
				switch {
				case data[p] < _words_trans_keys[_mid]:
					_upper = _mid - 2
				case data[p] > _words_trans_keys[_mid+1]:
					_lower = _mid + 2
				default:
					_trans += int((_mid - int(_keys)) >> 1)
					goto _match
				}
			}
			_trans += _klen
		}

	_match:
		cs = int(_words_trans_targs[_trans])

		if _words_trans_actions[_trans] == 0 {
			goto _again
		}

		_acts = int(_words_trans_actions[_trans])
		_nacts = uint(_words_actions[_acts])
		_acts++
		for ; _nacts > 0; _nacts-- {
			_acts++
			switch _words_actions[_acts-1] {
			case 0:
//line command.rl:30
				start = p
			case 1:
//line command.rl:31
				fields = append(fields, data[start:p])
//line command_parser.go:381
			}
		}

	_again:
		p++
		if p != pe {
			goto _resume
		}
	_test_eof:
		{
		}
	}

//line command.rl:42
	return fields
}
