// Code generated by Ragel; DO NOT EDIT.
package config

%%{
 machine command;
 alphtype byte;
 h = [ \t];
 tail = (h (any - '\n')*)?;
 main := (
  ('trust' h+ 'dscp' tail) @{ kind = trustDSCP } |
  ('protected-port' tail) @{ kind = protectedPort } |
  ('voice-vlan' tail) @{ kind = voiceVLAN } |
  ('jumbo' tail) @{ kind = jumboMode } |
  (('broadcast' | 'multicast' | 'unknown-unicast') h+ 'limit' tail) @{ kind = stormLimit }
 );
}%%
%% write data;

func commandKind(data string) (kind kind) {
 p, pe := 0, len(data)
 cs := 0
 %% write init;
 %% write exec;
 if cs < command_first_final { return unknown }
 return kind
}

%%{
 machine words;
 alphtype byte;
 action mark { start = p }
 action word { fields = append(fields, data[start:p]) }
 main := space* ((any - space)+ >mark %word space+)*;
}%%
%% write data;

func commandFields(data string) (fields []string) {
 data += " "
 p, pe := 0, len(data)
 cs, start := 0, 0
 %% write init;
 %% write exec;
 return fields
}
