// Code generated by Ragel; DO NOT EDIT.
package config

import "errors"

%%{
 machine configuration;
 alphtype byte;
 action start { start = p }
 action line {
  if err := document.line(data[start:p]); err != nil { return nil, err }
  if document.complete { fbreak; }
 }
 main := ((any - '\n')* >start '\n' @line)*;
}%%

%% write data;

func Parse(data string) (*Document, error) {
 document := &Document{}
 p, pe := 0, len(data)
 cs, start := 0, 0
 if pe == 0 || data[pe-1] != '\n' { data += "\n"; pe++ }
 %% write init;
 %% write exec;
 if !document.complete { return nil, errors.New("FastIron configuration output is incomplete") }
 return document, nil
}
