// Code generated by Ragel; DO NOT EDIT.
//
//line config.rl:1
package config

import "errors"

//line config.rl:15

//line parser.go:11
var _configuration_actions []byte = []byte{
	0, 1, 0, 1, 1, 2, 0, 1,
}

var _configuration_key_offsets []byte = []byte{
	0, 1,
}

var _configuration_trans_keys []byte = []byte{
	10, 10,
}

var _configuration_single_lengths []byte = []byte{
	1, 1,
}

var _configuration_range_lengths []byte = []byte{
	0, 0,
}

var _configuration_index_offsets []byte = []byte{
	0, 2,
}

var _configuration_trans_targs []byte = []byte{
	1, 0, 1, 0,
}

var _configuration_trans_actions []byte = []byte{
	3, 0, 5, 1,
}

const (
	configuration_start       int = 1
	configuration_first_final int = 1
	configuration_error       int = -1
)

const configuration_en_main int = 1

//line config.rl:18

func Parse(data string) (*Document, error) {
	document := &Document{}
	p, pe := 0, len(data)
	cs, start := 0, 0
	if pe == 0 || data[pe-1] != '\n' {
		data += "\n"
		pe++
	}

//line parser.go:57
	{
		cs = configuration_start
	}

//line config.rl:25

//line parser.go:62
	{
		var _klen int
		var _trans int
		var _acts int
		var _nacts uint
		var _keys int
		if p == pe {
			goto _test_eof
		}
	_resume:
		_keys = int(_configuration_key_offsets[cs])
		_trans = int(_configuration_index_offsets[cs])

		_klen = int(_configuration_single_lengths[cs])
		if _klen > 0 {
			_lower := int(_keys)
			var _mid int
			_upper := int(_keys + _klen - 1)
			for {
				if _upper < _lower {
					break
				}

				_mid = _lower + ((_upper - _lower) >> 1)
				switch {
				case data[p] < _configuration_trans_keys[_mid]:
					_upper = _mid - 1
				case data[p] > _configuration_trans_keys[_mid]:
					_lower = _mid + 1
				default:
					_trans += int(_mid - int(_keys))
					goto _match
				}
			}
			_keys += _klen
			_trans += _klen
		}

		_klen = int(_configuration_range_lengths[cs])
		if _klen > 0 {
			_lower := int(_keys)
			var _mid int
			_upper := int(_keys + (_klen << 1) - 2)
			for {
				if _upper < _lower {
					break
				}

				_mid = _lower + (((_upper - _lower) >> 1) & ^1)
				switch {
				case data[p] < _configuration_trans_keys[_mid]:
					_upper = _mid - 2
				case data[p] > _configuration_trans_keys[_mid+1]:
					_lower = _mid + 2
				default:
					_trans += int((_mid - int(_keys)) >> 1)
					goto _match
				}
			}
			_trans += _klen
		}

	_match:
		cs = int(_configuration_trans_targs[_trans])

		if _configuration_trans_actions[_trans] == 0 {
			goto _again
		}

		_acts = int(_configuration_trans_actions[_trans])
		_nacts = uint(_configuration_actions[_acts])
		_acts++
		for ; _nacts > 0; _nacts-- {
			_acts++
			switch _configuration_actions[_acts-1] {
			case 0:
//line config.rl:9
				start = p
			case 1:
//line config.rl:10

				if err := document.line(data[start:p]); err != nil {
					return nil, err
				}
				if document.complete {
					p++
					goto _out
				}

//line parser.go:147
			}
		}

	_again:
		p++
		if p != pe {
			goto _resume
		}
	_test_eof:
		{
		}
	_out:
		{
		}
	}

//line config.rl:26
	if !document.complete {
		return nil, errors.New("FastIron configuration output is incomplete")
	}
	return document, nil
}
