// Code generated by Ragel; DO NOT EDIT.
package config

import "strconv"

%%{
 machine route;
 alphtype byte;
 h = [ \t];
 token = (any - space)+;
 address = digit+ ('.' digit+){3};
 action mark { start = p }
 action prefix { route.prefix = data[start:p] }
 action mask { route.mask = data[start:p] }
 action gateway { route.gateway = data[start:p] }
 action options { route.options = true }
 destination = (address '/' digit+) >mark %prefix |
               address >mark %prefix h+ address >mark %mask;
 distance = 'distance' h+ digit+ >mark %{
  var err error
  route.distance, err = strconv.ParseInt(data[start:p], 10, 64)
  valid = valid && err == nil && route.distance >= 1 && route.distance <= 255
 };
 cost = digit+ >mark %options %{
  value, err := strconv.ParseUint(data[start:p], 10, 8)
  valid = valid && err == nil && value >= 1 && value <= 16
 };
 tag = 'tag' h+ digit+ >mark %options %{
  _, err := strconv.ParseUint(data[start:p], 10, 32)
  valid = valid && err == nil
 };
 name = 'name' h+ token %options;
 next_vrf = ('next-hop-vrf' h+ token | 'default-vrf') h+ %options;
 gateway = next_vrf? address >mark %gateway (h+ cost)? (h+ 'bfd' %options)?;
 other_hop = ('null0' | ('ethernet' | 'lag' | 'tunnel' | 've') h+ token (h+ cost)?) %{ route.ignored = true };
 main := 'ip' h+ 'route' h+ (
  'vrf' h+ token h+ (any - '\n')+ %{ route.ignored = true } |
  destination h+ (gateway | other_hop) (h+ distance)? (h+ name)? (h+ tag)?
 ) '\n';
}%%
%% write data;

func parseRoute(data string) (route routeSyntax, valid bool) {
 data += "\n"
 p, pe := 0, len(data)
 cs, start := 0, 0
 valid = true
 route.distance = 1
 %% write init;
 %% write exec;
 return route, valid && cs >= route_first_final
}
